// Worker 測試：模擬 Cloudflare 的 caches 與 fetch
import assert from 'assert';
const store = new Map();
globalThis.caches = { default: { match: async (r) => { const v = store.get(r.url); return v ? v.clone() : undefined; }, put: async (r, res) => { store.set(r.url, res); } } };
const calls = [];
let tdxStatus = 200;
globalThis.fetch = async (url, o = {}) => {
  calls.push({ url: String(url), o });
  if (String(url).includes('openid-connect/token')) return new Response(JSON.stringify({ access_token: 'TK', expires_in: 3600 }), { status: 200 });
  if (String(url).startsWith('https://tdx.transportdata.tw/api/basic/')) {
    assert.strictEqual(o.headers.authorization, 'Bearer TK');
    return new Response(JSON.stringify([{ ok: 1 }]), { status: tdxStatus, headers: { 'content-type': 'application/json' } });
  }
  if (String(url).startsWith('https://api.tomtom.com/')) return new Response(new Uint8Array([137, 80, 78, 71]), { status: 200, headers: { 'content-type': 'image/png' } });
  throw new Error('unexpected ' + url);
};
const W = (await import('./worker.js')).default;
const env = { TDX_ID: 'id', TDX_SECRET: 'sec', TOMTOM_KEY: 'tt' };
const pend = [];
const ctx = { waitUntil: (p) => pend.push(p) };
const req = (path, h = {}) => new Request('https://w.dev' + path, { headers: h });
const O = { Origin: 'https://catsans666-maker.github.io' };
let r = await W.fetch(req('/health', O), env, ctx);
assert.deepStrictEqual(await r.json(), { tdx: true, tomtom: true });
r = await W.fetch(req('/health', O), {}, ctx);
assert.deepStrictEqual(await r.json(), { tdx: false, tomtom: false });
r = await W.fetch(req('/tdx/v2/Rail/TRA/Station?$format=JSON', { Origin: 'https://evil.com' }), env, ctx);
assert.strictEqual(r.status, 403, '別的網站擋掉');
r = await W.fetch(req('/tdx/v2/Rail/TRA/Station?$format=JSON'), env, ctx);
assert.strictEqual(r.status, 403, '沒有來源擋掉');
r = await W.fetch(req('/tdx/v2/Rail/TRA/Station?%24format=JSON', O), env, ctx);
assert.strictEqual(r.status, 200);
assert.deepStrictEqual(await r.json(), [{ ok: 1 }]);
assert.strictEqual(r.headers.get('Access-Control-Allow-Origin'), O.Origin);
await Promise.all(pend);
const n = calls.length;
r = await W.fetch(req('/tdx/v2/Rail/TRA/Station?%24format=JSON', O), env, ctx);
assert.strictEqual(r.status, 200); assert.strictEqual(calls.length, n, '第二次走快取，不打 TDX');
assert.strictEqual(r.headers.get('Access-Control-Allow-Origin'), O.Origin);
tdxStatus = 429;
r = await W.fetch(req('/tdx/v2/Bus/EstimatedTimeOfArrival/City/Taipei?x=1', O), env, ctx);
assert.strictEqual(r.status, 429, '429 原樣傳回、不快取');
tdxStatus = 200;
r = await W.fetch(req('/tdx/v2/Bus/EstimatedTimeOfArrival/City/Taipei?x=1', O), env, ctx);
assert.strictEqual(r.status, 200);
r = await W.fetch(req('/tdx/notv2', O), env, ctx);
assert.strictEqual(r.status, 400);
r = await W.fetch(req('/tdx/v2/x', O), { TOMTOM_KEY: 'tt' }, ctx);
assert.strictEqual(r.status, 500); assert.ok((await r.json()).error.includes('TDX_ID'));
r = await W.fetch(req('/tomtom/relative0/12/3430/1753.png', { Referer: 'https://catsans666-maker.github.io/xinglu/' }), env, ctx);
assert.strictEqual(r.status, 200); assert.strictEqual(r.headers.get('content-type'), 'image/png');
const tt = calls.find((c) => c.url.startsWith('https://api.tomtom.com/'));
assert.ok(tt.url.includes('/flow/relative0/12/3430/1753.png?key=tt') && tt.o.headers.Referer.startsWith('https://catsans666-maker.github.io'));
r = await W.fetch(req('/tomtom/relative0/12/3430/1753.png', { Referer: 'https://evil.com/' }), env, ctx);
assert.strictEqual(r.status, 403);
r = await W.fetch(req('/tomtom/evil/1/2/3.png', O), env, ctx);
assert.strictEqual(r.status, 400);
r = await W.fetch(new Request('https://w.dev/tdx/v2/a', { method: 'OPTIONS', headers: O }), env, ctx);
assert.strictEqual(r.status, 204);
console.log('Worker 測試通過');
